version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload 